export const customerList_LAE = [
    { name: "Select Customer", inactive: true },
    { name: "Andersons Rabtrade Wholesale - (Lae)", inactive: false },
    { name: "Angau memorial hospital - (Lae)", inactive: false },
    { name: "Cash Customer - (LAE)", inactive: false },
    { name: "DURGA PACIFIC LIMITED - (LAE)", inactive: false },
    { name: "Frabelle(PNG) Ltd - (Lae)", inactive: false },
    { name: "Golden Apple Trading PTY LTD - (Lae)", inactive: false },
    { name: "G & M FLORES HOSPITAL LTD. - (Lae)", inactive: false },
    { name: "Hetadikaka Investment(LAE)", inactive: false },
    { name: "International Food Corporation Ltd. - (Lae)", inactive: false },
    { name: "KC 2 Limited(LAE)", inactive: false },
    { name: "Leannes Bakeshop - (Lae)", inactive: false },
    { name: "Lotus Enterprise - (Lae)", inactive: false },
    { name: "Markham valley High School - (Lae)", inactive: false },
    { name: "Menyamya High School - (LAE)", inactive: false },
    { name: "Morobe disaster office - (Lae)", inactive: false },
    { name: "Majestic seafood limited(LAE)", inactive: false },
    { name: "NCS Holdings Ltd - (Lae)", inactive: false },
    { name: "NAMBAWAN SEAFOODS PNG LTD. (LAE)", inactive: false },
    { name: "P.C & J.Y Woo Ltd - (Lae)", inactive: false },
    { name: "Papindo Trading Co Ltd - (Lae)", inactive: false },
    { name: "Raumai 18 Ltd - (Lae)", inactive: false },
    { name: "RH Trading Limited - (Lae)", inactive: false },
    { name: "Salu Investments - (Lae)", inactive: false },
    { name: "Seeto Kui(Holdings) LTD - (Lae)", inactive: false },
    { name: "Super Value Store - (Lae)", inactive: false },
    { name: "Star Mountain Paper Co Operation - (Lae)", inactive: false },
    { name: "Sinowell International(PNG) Ltd. - (Lae)", inactive: false },
    { name: "Seng Da Trading Limitied - (Lae)", inactive: false },
    { name: "Zenara Limited. - (Lae)", inactive: false },
]
